<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Save Transaction</name>
   <tag></tag>
   <elementGuidId>c8204ebd-8778-4882-af65-f4d54eda8b6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div/div/div[2]/div/div/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Save&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3016ecbf-097f-42e8-9b1e-1b28203ec59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>699ac547-f15e-416c-b3cf-e873a4fafde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>a2a365f9-c994-4a40-875e-b9d8f04c7b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:bg-success-600 relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] px-3 py-[7.6px] min-w-[26px] ring-inset shadow-sm rounded text-white dark:!text-success-900 bg-success dark:bg-success-300 ring-1 ring-success dark:ring-success-300 focus-visible:bg-success-600 focus-visible:ring-success-600 focus-visible:ring-offset-0 hover:bg-success-strong dark:hover:bg-success-400 hover:ring-success-strong dark:hover:ring-success-400 focus-visible:ring-1 focus-visible:ring-success-600 dark:focus-visible:ring-success-600 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none</value>
      <webElementGuid>45c78c7a-fcdd-44f9-ac65-5afce5ff3eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ts-section</name>
      <type>Main</type>
      <value>save-button</value>
      <webElementGuid>1df52517-f8e5-4356-ad00-49b3876910aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ca57752-7365-4766-8c41-01d386b0751d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>6771f369-7b6d-481f-a27b-2783b06a3dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-severity</name>
      <type>Main</type>
      <value>success</value>
      <webElementGuid>3f1e0c04-6d08-42a8-8d9d-97978b73004a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>92ed4125-7419-4205-912e-a8c531e98ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@tagsamurai/ts-mfe-settings-transaction&quot;)/div[@class=&quot;single-spa-container&quot;]/div[@class=&quot;rounded-lg bg-surface-0 dark:!bg-grayscale-900 text-general-800 dark:text-general-800&quot;]/div[@class=&quot;flex flex-col gap-3 p-6&quot;]/div[@class=&quot;flex flex-col gap-3 text-general-800 dark:text-general-100&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;flex justify-end items-center pt-3&quot;]/button[@class=&quot;focus:bg-success-600 relative items-center justify-center inline-flex text-center text-xs h-[26px] w-max min-w-[26px] px-3 py-[7.6px] min-w-[26px] ring-inset shadow-sm rounded text-white dark:!text-success-900 bg-success dark:bg-success-300 ring-1 ring-success dark:ring-success-300 focus-visible:bg-success-600 focus-visible:ring-success-600 focus-visible:ring-offset-0 hover:bg-success-strong dark:hover:bg-success-400 hover:ring-success-strong dark:hover:ring-success-400 focus-visible:ring-1 focus-visible:ring-success-600 dark:focus-visible:ring-success-600 transition duration-200 ease-in-out cursor-pointer overflow-hidden select-none&quot;]</value>
      <webElementGuid>d946d7e2-81aa-47ed-96e3-1d4d0b818904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>1830699f-aefb-4087-ade9-c3933d1a25bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-settings-transaction']/div/div[2]/div/div/div[2]/div[3]/button</value>
      <webElementGuid>c6f4dafe-822f-4e2f-8add-74ef92edf8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Timeout'])[1]/following::button[1]</value>
      <webElementGuid>d250a255-5320-4a91-a21d-093cff5dac92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>8ecd6b59-04ab-4ffe-8c35-fc2810342d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>1fc5e797-1a60-4fc9-afaa-8e3bbe42b524</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
