<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_no-replytagsamurai.com</name>
   <tag></tag>
   <elementGuidId>ccf81cf5-a991-4f3b-9795-7f4a65430b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='return false;']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16b8c86f-9128-4d6a-8547-3608abce38a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3afad638-5fd6-49be-a09f-bf60b597b96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>7496d935-62c8-42ac-a059-a676d43a2b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mailbox/indrafri/556894984</value>
      <webElementGuid>bf08ddcb-9856-4da1-9e23-8b6e9939c9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open email</value>
      <webElementGuid>40597c71-453e-4850-8a87-4e9027613988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>no-reply@tagsamurai.com</value>
      <webElementGuid>523eea6e-95bd-4566-952a-2a9e5e9f7021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;556894984&quot;)/td[2]/a[@class=&quot;email&quot;]</value>
      <webElementGuid>a1473614-a528-456f-b2f2-61ad6964f44f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='return false;']</value>
      <webElementGuid>7d8601fc-1f0e-4945-8ee6-a420f00b8fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='556894984']/td[2]/a</value>
      <webElementGuid>ae571920-d706-4041-8d49-cc64c83881f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'no-reply@tagsamurai.com')]</value>
      <webElementGuid>549536ea-65c1-4924-9255-075f8600ac3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/indrafri/556894984')]</value>
      <webElementGuid>c4fb05aa-829f-4cd7-9a02-6f8ba426e935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>db2a6266-9df7-42fd-aa15-6757b4f0726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/indrafri/556894984' and @title = 'Open email' and (text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>263c96c9-d408-4c02-9518-c84f472f20d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555380923']/td[2]/a</value>
      <webElementGuid>e7c2a476-04fc-44f7-9404-63060d99cc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/indrafr/555380923')]</value>
      <webElementGuid>5f5eaac6-6711-458f-a990-07027b8417b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/indrafr/555380923' and @title = 'Open email' and (text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>39017b7f-7fe7-4447-bc3a-561e85258231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555307021']/td[2]/a</value>
      <webElementGuid>4ef1ecc2-5b51-4b3f-bd21-0b55123e6ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/indraf/555307021')]</value>
      <webElementGuid>b93855f8-20ab-400d-9418-c032bbfeb9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/indraf/555307021' and @title = 'Open email' and (text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>4bc68505-9e5d-4d46-9dd9-bc098be05ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
