<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_no-replytagsamurai.com</name>
   <tag></tag>
   <elementGuidId>ccf81cf5-a991-4f3b-9795-7f4a65430b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='return false;']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5652768f-4eea-4a75-a668-e2f2a287463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e064aaec-a97f-451a-9d71-6c9c7a732529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return false;</value>
      <webElementGuid>3fcadfa8-6614-4213-ba56-4c63b46efcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mailbox/indrafr/555380923</value>
      <webElementGuid>a0276ed5-574d-4a57-b845-4a17c4d081ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open email</value>
      <webElementGuid>aff56498-ca7b-4580-b581-a3bd2e2b8930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>no-reply@tagsamurai.com</value>
      <webElementGuid>88bc0fe9-cb6d-4e44-80d0-5ea36ee691f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;555380923&quot;)/td[2]/a[@class=&quot;email&quot;]</value>
      <webElementGuid>4c0d9d7f-e7e2-4a62-aea6-9a0b3ee21618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='return false;']</value>
      <webElementGuid>5a483375-2e42-45bd-8fb3-3b08d5d8947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555380923']/td[2]/a</value>
      <webElementGuid>e7c2a476-04fc-44f7-9404-63060d99cc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'no-reply@tagsamurai.com')]</value>
      <webElementGuid>ec96de58-2ca7-4716-a0ac-41c2258a5d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/indrafr/555380923')]</value>
      <webElementGuid>5f5eaac6-6711-458f-a990-07027b8417b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>f9b3689a-a77e-4e4a-b3a0-82f59671067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/indrafr/555380923' and @title = 'Open email' and (text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>39017b7f-7fe7-4447-bc3a-561e85258231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555307021']/td[2]/a</value>
      <webElementGuid>4ef1ecc2-5b51-4b3f-bd21-0b55123e6ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mailbox/indraf/555307021')]</value>
      <webElementGuid>b93855f8-20ab-400d-9418-c032bbfeb9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mailbox/indraf/555307021' and @title = 'Open email' and (text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>4bc68505-9e5d-4d46-9dd9-bc098be05ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
