<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Activate Account</name>
   <tag></tag>
   <elementGuidId>a498f537-a7ee-42dd-9d70-ea95db244658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/table/tbody/tr[2]/td/div/div/div/div/div/div[2]/div[3]/a/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b365c488-f42f-4a7f-b33e-355733bb923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Activate Account
          </value>
      <webElementGuid>773adf2f-03bb-4816-8e78-93aae903489a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_html_555380923&quot;)/div[2]/div[3]/a[1]/button[1]</value>
      <webElementGuid>3b18a43c-2eaf-4101-8c84-7077e386354d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text_html_555380923']/div[2]/div[3]/a/button</value>
      <webElementGuid>5068447c-476b-4034-bf25-513ed8737ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f5ce7faf-d1ca-4e13-a572-c333307e7abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
            Activate Account
          ' or . = '
            Activate Account
          ')]</value>
      <webElementGuid>3e3ebb75-d193-4142-990a-f4b6ba33fd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='text_html_555259853']/div[2]/div[3]/a/button</value>
      <webElementGuid>9b23ac09-a94c-4e55-95de-a137aadde7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
