<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsm</name>
   <tag></tag>
   <elementGuidId>d1e7b3a1-b87b-471b-8e77-b57c294df86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b97443c-47cc-4fe4-a5bd-0c782808bab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>af242fbd-b50b-4d23-acbd-e373cb7e0224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sm</value>
      <webElementGuid>2c4a62a1-2331-4bd5-8fa5-5ce8aeb86590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>30f6859a-e15e-46c3-8122-c73a241eb333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm&quot;)</value>
      <webElementGuid>7ed71868-eda6-45c5-bd28-592bd9ea8dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sm']</value>
      <webElementGuid>42a9b99b-1793-4d5c-a741-f51a1ef0f130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form']/form/input[2]</value>
      <webElementGuid>f78ec8eb-d792-4097-acff-16eec1be3274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>abd9873c-7c16-4e19-90e0-0d717c57e840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'sm']</value>
      <webElementGuid>1d9f51f7-87ca-4cb7-b140-d62add51d6f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
