<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mailbox</name>
   <tag></tag>
   <elementGuidId>84155eab-188f-4e0c-9106-b2de38027cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mailbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mailbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d31a7ee-dadc-4441-9838-bca275be77a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9074cdcd-13f2-418d-8443-976f55a3bae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>56ffda9a-aa7f-41cb-ad06-1c6801376002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9a52e9be-0758-46ba-9b43-9acc65d3f7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0f25dbcd-85c6-43b7-910c-67facbebfa42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>e350f61f-249d-4cf4-9e55-84735b0bbde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.value = this.value;</value>
      <webElementGuid>8bab8286-94c9-4aca-9019-d8a84f207b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mailbox</value>
      <webElementGuid>cf3f86f5-9e0c-4ffe-adb6-1b911d6a542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type mailbox and press ENTER</value>
      <webElementGuid>1ba9d37f-3af8-4238-8b93-ea07a1b0eb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailbox&quot;)</value>
      <webElementGuid>681b6c30-a589-489d-a824-b9fe00d74fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mailbox']</value>
      <webElementGuid>e122145d-e3dd-4280-b28e-dd4485191cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form']/form/input</value>
      <webElementGuid>9897d1fc-6896-4484-a264-e57f7c017786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8f517331-701d-455c-9146-12ef752690da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mailbox' and @id = 'mailbox' and @placeholder = 'Type mailbox and press ENTER']</value>
      <webElementGuid>07c94d67-0dd9-430e-b36e-b8b52b340d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
