<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_no-replytagsamurai.com</name>
   <tag></tag>
   <elementGuidId>9eb3d867-d3c6-43a6-82f8-45d5372529c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='555259853']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53c583d3-eae1-4058-86fc-ad2d07b37029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>no-reply@tagsamurai.com</value>
      <webElementGuid>0a66e78c-03ab-4cf3-9dfb-5c05fbed65c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;555259853&quot;)/td[2]</value>
      <webElementGuid>ebfd2545-9e26-46fb-b501-c810e77d9fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555259853']/td[2]</value>
      <webElementGuid>59ac4ccb-33e2-46e5-a56d-5fdb437a2997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>682498f2-a08e-4634-9237-cd7bff8778a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>2a4431f8-62d3-4578-b84d-6492442faa4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
