<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_no-replytagsamurai.com</name>
   <tag></tag>
   <elementGuidId>9eb3d867-d3c6-43a6-82f8-45d5372529c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/table/tbody/tr[1]/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8a31b614-3c19-474b-b298-02e12c48da29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>no-reply@tagsamurai.com</value>
      <webElementGuid>ad8a7f15-64f9-47b2-89b5-4361006571ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;555259853&quot;)/td[2]</value>
      <webElementGuid>589c9b89-97ba-40ce-9224-d58e1802f08e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='555259853']/td[2]</value>
      <webElementGuid>df1f958a-75fd-474f-ab39-53d1528db25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>aa0b7f07-26e5-4b68-bc27-658e1465bdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'no-reply@tagsamurai.com' or . = 'no-reply@tagsamurai.com')]</value>
      <webElementGuid>7a875097-46ac-4983-9fc5-e84dc3d8feb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
