<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>e1167162-24d9-408a-83c3-e3d2c1f39c1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a4760b1b-b042-4926-8e9c-18d4179d35a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>81756984-1876-48e2-a98d-209cae403eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7mFU5Tu3_OgXb83xdqBUnuduqXtK4QT9jQ9s72lQW-D99LQruwePkJyr6w3uSt8wKMyJdr5xDbi1H_K5Ew52Ame89q8Y3no8l_qxR2eMhD3wgym8Lrx0jlJe7bpGvqf2HeRjU28d1v_SaZou9S2HuAC9v799H5c8hUnLHiZS10Fmr8DgeI5s18xPYBHTP9ZgC5pzZG&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij</value>
      <webElementGuid>5a29ca37-0096-4cc9-be99-7251df30b9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>d6347134-0259-4662-ae2b-6ed88cde827e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/User Basic - My Asset Task Assignment/OBJ 006 History My Asset/Page_TAG SAMURAI/iframe_html1body1div2div4iframe1_c-fdwit497cnu2</value>
      <webElementGuid>5ccd1e4a-d25a-4617-a3d0-2743f4efcd25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>2460f32d-6a99-4354-bfea-65257ab4a4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7mFU5Tu3_OgXb83xdqBUnuduqXtK4QT9jQ9s72lQW-D99LQruwePkJyr6w3uSt8wKMyJdr5xDbi1H_K5Ew52Ame89q8Y3no8l_qxR2eMhD3wgym8Lrx0jlJe7bpGvqf2HeRjU28d1v_SaZou9S2HuAC9v799H5c8hUnLHiZS10Fmr8DgeI5s18xPYBHTP9ZgC5pzZG&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij')])[6]</value>
      <webElementGuid>3480d0b4-2387-4e33-9ad0-ccaa10146f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>b4ad57ad-7d40-41d8-98ac-0cb5e61d9dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7mFU5Tu3_OgXb83xdqBUnuduqXtK4QT9jQ9s72lQW-D99LQruwePkJyr6w3uSt8wKMyJdr5xDbi1H_K5Ew52Ame89q8Y3no8l_qxR2eMhD3wgym8Lrx0jlJe7bpGvqf2HeRjU28d1v_SaZou9S2HuAC9v799H5c8hUnLHiZS10Fmr8DgeI5s18xPYBHTP9ZgC5pzZG&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij']</value>
      <webElementGuid>7d0c12a0-d2e4-4524-8d3d-82d92f52b642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
