<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select asset</name>
   <tag></tag>
   <elementGuidId>d6f6db4a-eb6e-4bb9-b3a0-01dcee9d7c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='license-audit-fixed-asset-audit-list']/div/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Row Unselected&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>79fad5fa-330a-44bd-b849-17845d73eeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap</value>
      <webElementGuid>89e08c7a-7f2f-4ecc-9784-b6973bc03212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>469a876d-1592-4d54-b184-00f4ce449464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>e583c943-dea6-4f68-aa66-17df25972ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>bodycell</value>
      <webElementGuid>c3b88e97-8844-4b08-b453-3ae7ec1ced33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-selection-column</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d888da24-8c7e-4b34-9a67-43466876aed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-editable-column</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb0b5804-6020-4db2-b88a-62ba8595724d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-cell-editing</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b358e84-4326-4d5d-8a8b-56472956b802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;license-audit-fixed-asset-audit-list&quot;)/div[@class=&quot;relative rounded-lg rounded-br-none rounded-bl-none&quot;]/table[@class=&quot;w-full !border-separate !border-spacing-0 border !border-solid !border-general-100 !border-t-0 !border-l-0 !border-r-0 !rounded-lg&quot;]/tbody[@class=&quot;[&amp;_tr:last-of-type>td]:!border-b-0 [&amp;_tr:last-of-type>td:last-child]:!rounded-br-lg [&amp;_tr:last-of-type>td:first-child]:!rounded-bl-lg&quot;]/tr[@class=&quot;!text-general-800 dark:text-general-50 bg-transparent dark:bg-transparent focus:outline-none focus:outline-offset-0 transition duration-200 cursor-pointer&quot;]/td[@class=&quot;[&amp;[data-p-frozen-column=true]:empty]:bg-transparent !text-general-800 !dark:text-general-800 text-xs font-medium leading-[16.39px] tracking-[0.02em] overflow-hidden text-left border-0 !border-b !border-solid border-general-100 dark:border-general-500 py-[4.5px] px-2 min-h-6 space-nowrap text-nowrap w-max whitespace-nowrap&quot;]</value>
      <webElementGuid>73060b67-e66c-4ada-ba44-c5f0336e5f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='license-audit-fixed-asset-audit-list']/div/table/tbody/tr/td</value>
      <webElementGuid>e03028b2-8e1d-485d-815d-d1d9dd43444c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TAG'])[5]/following::td[1]</value>
      <webElementGuid>4b25bf38-f589-4c51-a5b9-e37449fa2d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Asset'])[3]/following::td[1]</value>
      <webElementGuid>f97f55b7-050d-4581-9519-6a34b89dd329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID'])[1]/preceding::td[3]</value>
      <webElementGuid>32347500-6d4f-43b5-9cc4-1fee9412c8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/table/tbody/tr/td</value>
      <webElementGuid>aa1f2f78-e07f-4fd2-8262-66b9cc54f9ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
