<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Date User Log Login</name>
   <tag></tag>
   <elementGuidId>67003355-8294-4113-84e9-031c62b7bac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_132_panel']/div/div/div[2]/table/tbody/tr[5]/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;30&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7156fa70-84ad-4ebe-a575-4ad2df107abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c2e3f08-7636-4e5e-91a3-d0cb2b72c736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09e204dd-5bb9-48c5-a3c7-2ae3f47f2c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center w-8 h-8 rounded-full text-general-800 bg-general-100 dark:text-general-100 dark:bg-general-300 hover:bg-general-50 dark:hover:bg-general-300 cursor-pointer</value>
      <webElementGuid>4c8afaaa-e858-499f-9c8e-01ff87c76fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>daylabel</value>
      <webElementGuid>80852583-13f9-4126-91a7-05f06ed6609c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ebbd518-d1cc-4dc1-87d2-41e3212c70ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-highlight</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b6c1a24-0aee-4fa7-977b-1424c0536acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-group-section</name>
      <type>Main</type>
      <value>tablebodycelllabel</value>
      <webElementGuid>d4102c88-e408-4c7d-9c43-703fb966c881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f62c6e0c-ba74-42ef-b827-5c73f7cfb1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5a4bd81d-cecd-4cf4-bbe7-24fe39f333e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_132_panel&quot;)/div[@class=&quot;flex w-full&quot;]/div[@class=&quot;w-full&quot;]/div[2]/table[@class=&quot;block w-[224px] [&amp;_tbody]:block [&amp;_tbody]:w-[224px] m-0 [&amp;_th]:text-xs [&amp;_td]:text-xs [&amp;_th]:font-medium [&amp;_td]:font-medium [&amp;_th]:text-general-800 [&amp;_td]:text-general-800 dark:[&amp;_th]:text-general-100 dark:[&amp;_td]:text-general-100 [&amp;_[data-p-other-month=&quot;true&quot;]]:invisible&quot;]/tbody[1]/tr[5]/td[@class=&quot;p-0&quot;]/span[@class=&quot;flex items-center justify-center w-8 h-8 rounded-full text-general-800 bg-general-100 dark:text-general-100 dark:bg-general-300 hover:bg-general-50 dark:hover:bg-general-300 cursor-pointer&quot;]</value>
      <webElementGuid>0b8e8c2c-2d82-4adf-bdf4-3bd83a9b57aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_132_panel']/div/div/div[2]/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>0711c974-31ab-4f3e-824a-755404bde348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[30]</value>
      <webElementGuid>8f3b3fe1-a9ac-41c8-8670-b8cfa3de61e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[31]</value>
      <webElementGuid>35a8fe0c-a909-413b-a436-eecc9ec01e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='30']/parent::*</value>
      <webElementGuid>f2987b53-ea9b-4b29-97b8-f9a904454a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[5]/td[2]/span</value>
      <webElementGuid>fe341bf8-f22e-4544-9fd0-9ef127617963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '30' or . = '30')]</value>
      <webElementGuid>c4e5adb7-2d1f-43c9-b4e6-c45a4156ea49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
