<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ASDF .ai V2_button-icon-6454c4253dd1017f28689572</name>
   <tag></tag>
   <elementGuidId>3d4e6bdb-cc8f-40aa-ae0a-8aaccbf39b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-icon-6454c4253dd1017f28689572</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='button-icon-6454c4253dd1017f28689572']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button-action-6454c4253dd1017f28689572</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7d253a38-0ca7-4aad-b8ee-07aa5326c084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-icon-6454c4253dd1017f28689572</value>
      <webElementGuid>b1fb9a5f-5713-479d-a754-343f6b6c2f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>single-action-menu</value>
      <webElementGuid>40cc9718-3b1d-472b-b852-2f62fe42e94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon ic-ellipsis-h text-primary cursor-pointer</value>
      <webElementGuid>e182dd6c-3431-4777-942b-8134e4165ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-tooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4718a74-58ea-42fa-8b09-4dd6c0b10050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-icon-6454c4253dd1017f28689572&quot;)</value>
      <webElementGuid>2e3398ca-033d-4002-9053-e10e0625834d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='button-icon-6454c4253dd1017f28689572']</value>
      <webElementGuid>e6f0e606-bb6c-4b0b-8440-cfd7d79b236b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-action-6454c4253dd1017f28689572']/i</value>
      <webElementGuid>4484d51b-e286-48f5-8e11-f440bbfa48c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/button/i</value>
      <webElementGuid>0e2cac8b-bdb1-4238-af02-27b93b0b04f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'button-icon-6454c4253dd1017f28689572']</value>
      <webElementGuid>9c2fb48f-4ca7-4350-8ba2-68c63910d380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
