<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Field 1 Category</name>
   <tag></tag>
   <elementGuidId>93f19d29-463a-4c74-917b-b187a57cba75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[8]/div/div[2]/div/div/ul/li/ul/li[1]/div/div/div/label/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Not Selected Aksesori$/ >> internal:label=&quot;Not Selected&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60114aa4-f21f-4af5-a0eb-1c666cab24e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eedba24a-f5a4-42b0-bcb9-375030bd5a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-checkbox-input peer w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none border-2 border-surface-300 dark:border-surface-700 appareance-none cursor-pointer</value>
      <webElementGuid>613a0071-69f4-47ff-9325-c700a52fb780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88e0dd1f-d87c-4a39-a9d8-73078636e1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1728380568555&quot;)/div[@class=&quot;overflow-auto&quot;]/ul[@class=&quot;m-0 p-0 list-none overflow-auto&quot;]/li[@class=&quot;p-[2px] rounded-md focus:outline-none focus:outline-offset-0&quot;]/ul[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/li[@class=&quot;!m-0 list-none p-0 !pl-1&quot;]/div[@class=&quot;flex items-center rounded-md p-1 text-surface-700 dark:text-surface-700 transition-shadow duration-200 cursor-pointer&quot;]/div[@class=&quot;relative inline-flex align-bottom w-4 h-4 mr-2 cursor-default select-none&quot;]/div[@class=&quot;flex items-center justify-center w-4 h-4 rounded border text-surface-600 border-surface-300 bg-surface-0 dark:border-surface-700 dark:bg-surface-900 peer-focus-visible:ring-2 peer-focus-visible:ring-primary-500 dark:peer-focus-visible:ring-primary-400 transition-colors duration-200&quot;]/label[@class=&quot;flex w-max text-xs font-medium text-general-800 dark:text-general-100 items-center cursor-pointer&quot;]/div[@class=&quot;p-tristatecheckbox p-checkbox p-component relative w-4 h-4 inline-flex align-bottom transition-all duration-200&quot;]/input[@class=&quot;p-checkbox-input peer w-full h-full absolute top-0 left-0 z-10 p-0 m-0 rounded border opacity-0 rounded-md outline-none border-2 border-surface-300 dark:border-surface-700 appareance-none cursor-pointer&quot;]</value>
      <webElementGuid>2392e597-c713-473a-93f6-db09e6ad6b84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[21]</value>
      <webElementGuid>47b9ffc6-cdcb-4270-a6b0-e5e6c01955c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1728380568555']/div/ul/li/ul/li/div/div/div/label/div/input</value>
      <webElementGuid>93c75154-00f4-40ff-a15b-bf1da7d23eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/ul/li/div/div/div/label/div/input</value>
      <webElementGuid>82ca87b9-8cae-4d0d-bfff-99f49ab112bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>5ef3cb57-3b0a-4f49-9d33-11ef88e07a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
