<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_19</name>
   <tag></tag>
   <elementGuidId>4d2a7392-96dc-428b-a4ec-1a389f7bb012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_64_panel']/div/div/div[2]/table/tbody/tr[3]/td[5]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;19&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4914acc7-2ae4-4796-88bf-134cf58ac915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e9d6eca-0c47-45c6-8220-d75da928fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>094b22d3-d2f6-4303-9875-4d2bd7ea557c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center justify-center w-8 h-8 rounded-full text-general-800 dark:text-general-100 bg-transparent hover:bg-general-50 dark:hover:bg-general-300 cursor-pointer</value>
      <webElementGuid>feab3776-787c-4571-b76d-970c563d96f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>daylabel</value>
      <webElementGuid>173afa0c-c6e8-4572-b836-0d0340a2b76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>30b8dafc-1dab-46cb-b803-41a6ba02dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-highlight</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>945bc270-65b2-45dd-a122-e6ee8215f0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-group-section</name>
      <type>Main</type>
      <value>tablebodycelllabel</value>
      <webElementGuid>d3920199-3277-4526-b238-7c78914a952e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e581824-d15b-4033-9749-4ac513600f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>9c711b17-3fec-4a1f-bf45-dec3d42921a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_64_panel&quot;)/div[@class=&quot;flex w-full&quot;]/div[@class=&quot;w-full&quot;]/div[2]/table[@class=&quot;block w-[224px] [&amp;_tbody]:block [&amp;_tbody]:w-[224px] m-0 [&amp;_th]:text-xs [&amp;_td]:text-xs [&amp;_th]:font-medium [&amp;_td]:font-medium [&amp;_th]:text-general-800 [&amp;_td]:text-general-800 dark:[&amp;_th]:text-general-100 dark:[&amp;_td]:text-general-100 [&amp;_[data-p-other-month=&quot;true&quot;]]:invisible&quot;]/tbody[1]/tr[3]/td[@class=&quot;p-0&quot;]/span[@class=&quot;flex items-center justify-center w-8 h-8 rounded-full text-general-800 dark:text-general-100 bg-transparent hover:bg-general-50 dark:hover:bg-general-300 cursor-pointer&quot;]</value>
      <webElementGuid>d17fb1c8-c1db-47cd-aa9b-9abc3b92950d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pv_id_64_panel']/div/div/div[2]/table/tbody/tr[3]/td[5]/span</value>
      <webElementGuid>cda74233-a6fd-4e29-9ee4-7482057f44ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[19]</value>
      <webElementGuid>053d1ac2-6070-48ae-8853-38855584b4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[20]</value>
      <webElementGuid>7db7c1e2-8965-480c-9fb7-9f252c9a14f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>626d3c82-9cfc-4be1-8a76-559a211bd962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/span</value>
      <webElementGuid>ee4a7ce6-59fd-4a56-ad15-fbd13530d59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '19' or . = '19')]</value>
      <webElementGuid>9985b4eb-392c-45ea-981c-64573157d376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
