<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motorcycles_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>09a18481-5689-4807-b20c-8e6616c77664</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd368977-a566-4ce4-9c2f-2fa6b2cd58cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>e7328d4a-439a-443f-99ef-bef94fc25988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6_ycv_psjllF0TK7sRY-NtC3Qf2TiT2I9gskUaMg4ZfMobe0kcphsUGIn_7fYHPf587Y5BPGCTj1xFdsglee7iimn_eIhb_PSbCDZgG7Ldwru-urWjcBTe_xmrsIwMz6ty_hdgmyVdKyxhPunsRtBPlhQy-BULuklqU4YfkUz6PrXWAYmLu4TYM5Lq_uX8fJ-eAmUGHDkEphteaaYyyh8-uEHoJA&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij</value>
      <webElementGuid>49e82118-bb39-4451-b381-e73fc99c6e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>923a8ece-921b-4a33-a671-317a19ef6e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OBJ User Profile/001 System Role/Page_TAG SAMURAI/iframe_html1body1div2div4iframe1_c-4la2okydii6x</value>
      <webElementGuid>914f6c25-1e67-4730-a6d6-b77ca659133b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>86634b69-806b-4db2-a53b-967a52c3cef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6_ycv_psjllF0TK7sRY-NtC3Qf2TiT2I9gskUaMg4ZfMobe0kcphsUGIn_7fYHPf587Y5BPGCTj1xFdsglee7iimn_eIhb_PSbCDZgG7Ldwru-urWjcBTe_xmrsIwMz6ty_hdgmyVdKyxhPunsRtBPlhQy-BULuklqU4YfkUz6PrXWAYmLu4TYM5Lq_uX8fJ-eAmUGHDkEphteaaYyyh8-uEHoJA&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij')])[6]</value>
      <webElementGuid>d048b68d-50a6-4cc3-8e24-9a06ddce6497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>429df62a-2139-49da-a61b-af311b52a45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6_ycv_psjllF0TK7sRY-NtC3Qf2TiT2I9gskUaMg4ZfMobe0kcphsUGIn_7fYHPf587Y5BPGCTj1xFdsglee7iimn_eIhb_PSbCDZgG7Ldwru-urWjcBTe_xmrsIwMz6ty_hdgmyVdKyxhPunsRtBPlhQy-BULuklqU4YfkUz6PrXWAYmLu4TYM5Lq_uX8fJ-eAmUGHDkEphteaaYyyh8-uEHoJA&amp;k=6Ld0AFggAAAAABDo0r9re30475bd1yUWlxY4Qtij']</value>
      <webElementGuid>86bbbf0a-1a7b-49d1-8057-6c85697e797c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
