<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User ASDF Tag Samurai</name>
   <tag></tag>
   <elementGuidId>aeb4946d-dc94-4791-9f91-544add247e17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-icon-6454c4253dd1017f28689572</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='button-icon-6454c4253dd1017f28689572']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button-action-6454c4253dd1017f28689572</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>34448570-1c98-40ad-b9ba-9b38119553a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-icon-6454c4253dd1017f28689572</value>
      <webElementGuid>507ef88b-03eb-4f1f-b459-20302ac3307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>single-action-menu</value>
      <webElementGuid>7e4cc38a-b765-4aa2-b53b-f7025f2ec438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon ic-ellipsis-h text-primary cursor-pointer</value>
      <webElementGuid>3033f884-2570-4ba3-ba48-70f5e2ad255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-tooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0be47932-1b44-45a6-a2b0-73faa6a5dd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-icon-6454c4253dd1017f28689572&quot;)</value>
      <webElementGuid>79bef1ba-70c9-4327-b8c4-952a9e8a4b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='button-icon-6454c4253dd1017f28689572']</value>
      <webElementGuid>d0edcf4b-3554-4776-9734-52df545b6d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-action-6454c4253dd1017f28689572']/i</value>
      <webElementGuid>fc6b2f0e-36e6-41d2-a8b2-78e91f49974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/button/i</value>
      <webElementGuid>cca735cd-50d2-42d7-b2c2-a897db16577d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'button-icon-6454c4253dd1017f28689572']</value>
      <webElementGuid>33175a30-809a-40a4-bc28-25b0c6a90900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
