<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Changelog Role</name>
   <tag></tag>
   <elementGuidId>6a4232bb-b128-4616-b6b7-d6149bf5a202</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div/div/div[2]/div/div/div[2]/div[1]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08a8237c-d701-483a-b7d8-fbcd0d57410d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dialog-header-icon p-dialog-header-close p-link relative flex items-center justify-center w-6 h-6 !p-0.5 border-0 rounded-full text-general-200 bg-transparent transition duration-200 ease-in-out hover:bg-general-50 dark:hover:bg-grayscale-800 hover:text-general-300 overflow-hidden</value>
      <webElementGuid>a6c2138c-f762-4561-9dd4-43520b0adcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>040d04af-7880-4455-938d-9ed6100a6121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff857740-56e0-415b-bc02-51d500a05c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>closebutton</value>
      <webElementGuid>961e35fc-4e3b-4634-8f57-6da82d4e685b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-group-section</name>
      <type>Main</type>
      <value>headericon</value>
      <webElementGuid>ae48ad8c-1d69-4fb0-bd37-9008021be29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-dialog-mask p-component-overlay p-component-overlay-enter transition duration-300 has-[.mask-active]:bg-transparent dark:has-[.mask-active]:bg-transparent bg-dialog-mask dark:dialog-mask has-[.mask-active]:backdrop-blur-none backdrop-blur-sm&quot;]/div[@class=&quot;p-dialog p-component p-ripple-disabled w-[800px] !z-50 rounded-[0.4375em] shadow-[box-shadow: -4px 4px 20px 0px #0000001A] flex flex-col p-6 gap-3 bg-white dark:bg-grayscale-900 max-h-[90vh] sm:max-w-[90vw] m-0 transform scale-100&quot;]/div[@class=&quot;p-dialog-header flex items-center justify-between gap-2 shrink-0 rounded-tl-lg rounded-tr-lg text-header-weak dark:text-general-100&quot;]/div[@class=&quot;p-dialog-header-icons flex items-center ml-auto&quot;]/button[@class=&quot;p-dialog-header-icon p-dialog-header-close p-link relative flex items-center justify-center w-6 h-6 !p-0.5 border-0 rounded-full text-general-200 bg-transparent transition duration-200 ease-in-out hover:bg-general-50 dark:hover:bg-grayscale-800 hover:text-general-300 overflow-hidden&quot;]</value>
      <webElementGuid>88f08481-3893-42c6-b394-54c6e07be42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[49]</value>
      <webElementGuid>67654ddd-ffbd-4fab-9c85-2e89a23120d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Changelog: Role > Borrowing/Assignment'])[1]/following::button[1]</value>
      <webElementGuid>7caa252e-e588-470a-ac0c-9f352466630d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Level'])[1]/following::button[1]</value>
      <webElementGuid>98db4444-4f7d-440b-8f62-5bec0cf26afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::button[4]</value>
      <webElementGuid>b032c740-5102-4827-8e34-f73b8bf2b705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/preceding::button[4]</value>
      <webElementGuid>d145613e-e68f-4493-8ac5-e08501a3acc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>c5bb0d2e-694c-4ccb-99ce-52088134ef0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>70955684-5150-4594-839c-48eddea92513</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
