<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select User</name>
   <tag></tag>
   <elementGuidId>5309305b-1c6d-4fbe-985e-74c81777ca2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-icon-66fa1f8d100aa413b09cfd69</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='button-icon-66fa1f8d100aa413b09cfd69']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Row Unselected John Abruzzi Basic QA IT ASDF ..ai V2 9/30/24, 10:52:38 AM&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d173d1ba-bdb1-4005-b27b-27ffc083211a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-icon-66fa1f8d100aa413b09cfd69</value>
      <webElementGuid>27ee7ab6-736d-43ae-a28a-07618fd024d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>single-action-menu</value>
      <webElementGuid>a563d27c-b8aa-4bca-9b98-381c2fdc770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon ic-ellipsis-h text-primary cursor-pointer</value>
      <webElementGuid>d36c4efd-e658-41db-b8cc-e49873d5c8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pd-tooltip</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95993901-0618-49c6-aaaf-cc082ce4a5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-icon-66fa1f8d100aa413b09cfd69&quot;)</value>
      <webElementGuid>9b700719-fb50-445b-924f-7ac25dff2f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='button-icon-66fa1f8d100aa413b09cfd69']</value>
      <webElementGuid>c9a81f91-34b8-4393-a97c-40c2f1e1bc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-action-66fa1f8d100aa413b09cfd69']/i</value>
      <webElementGuid>a9683626-768f-41b1-a2c2-211be43b8f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/button/i</value>
      <webElementGuid>b405a017-5123-4320-9afe-9eb3a792e9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'button-icon-66fa1f8d100aa413b09cfd69']</value>
      <webElementGuid>fe7dece6-0705-4769-ba1c-033e232072ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
