<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select report type</name>
   <tag></tag>
   <elementGuidId>278693a5-3a70-472f-8d46-961001de8b54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_70</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pv_id_70']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba054ba5-fc1f-4f04-83a6-d11cd107503c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>customvalidation</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>cd285cba-638f-4752-8496-ffbb8c426d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Report Type</value>
      <webElementGuid>d3cd0dfc-0ec1-49ef-b3d5-1793daed576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldname</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>dd01f3a2-5606-481a-ab26-57730fa93d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c1669c61-c01d-4412-bf60-6c2549374660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usevalidator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f3038a3-195f-4ebb-a858-cb963f6cc9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a170dc66-ab0a-41d2-a549-e4499cc241f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatvalidatormessage</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7c93060-d8c0-4485-996c-577dbde835dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Report Typeerror</value>
      <webElementGuid>ea2b9fdd-210d-447b-9b61-234aaebafcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex relative w-full cursor-default select-none</value>
      <webElementGuid>23664fa8-1cd7-447b-bf19-033b010387a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7f6e8eb9-fe4d-4b52-b1c0-b6efcfe5968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>2e358a2e-6776-4aef-991f-ad929ddd91b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_70</value>
      <webElementGuid>d3fe992a-6de0-4202-9222-57dd8abdac0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select report type</value>
      <webElementGuid>1adeebe7-d500-4bc1-893e-f1910c7fbabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_70&quot;)</value>
      <webElementGuid>eb6d53af-afb8-49f8-85a2-fc79c0140ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pv_id_70']</value>
      <webElementGuid>562abae5-8d14-4347-8ec2-60cfc4b29494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-log-report']/div/div[2]/div/div/form/div/div/div[2]/div/div</value>
      <webElementGuid>5b98652b-2579-4f51-ae85-8de05289ad48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div</value>
      <webElementGuid>346768b1-cf62-4c27-af74-a7e561a9997b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pv_id_70' and (text() = 'Select report type' or . = 'Select report type')]</value>
      <webElementGuid>a20f7943-13dd-45b5-8892-5cec3ed70f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
