<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select time interval</name>
   <tag></tag>
   <elementGuidId>2134ff14-d54b-4670-8d36-0db1c9d35b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div/div/div[2]/div/div/form/div[1]/div[1]/div[4]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_72</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c6ff9aa-fd4b-4af8-9457-74e1750bce4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>customvalidation</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f495d1c0-a4e6-4efa-81ae-20c818e48dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Time Interval</value>
      <webElementGuid>d4ffe370-7077-4753-be0b-30731b9ebd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldname</name>
      <type>Main</type>
      <value>interval.label</value>
      <webElementGuid>d696c078-db08-40ac-83f1-22faeed146a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usevalidator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ded21b3-8ba1-4f1f-b083-0cd2ef6adb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cce0c44d-a6b1-4c5b-bae7-4c232cbd417b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatvalidatormessage</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94d2af4d-ed10-4a8c-918b-0a4bd9f98f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Time Intervalerror</value>
      <webElementGuid>80dc39a1-9f64-4ea3-8ced-d6a3fba3dc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex relative w-full cursor-default select-none</value>
      <webElementGuid>3ab38b21-5e64-4a0a-b698-939c8205c05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ec2bc1ca-33d1-4503-8aec-cd8fcd786feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>a2b4bd41-65f4-45ed-9603-1a4aa7446a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_72</value>
      <webElementGuid>bd20909b-bcb3-48f6-8515-a0493dfc8f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select time interval</value>
      <webElementGuid>a695ede2-c282-45f8-9746-633d375bdbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_72&quot;)</value>
      <webElementGuid>6abddf5f-8990-43ee-8ea7-97731e43d1a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pv_id_72']</value>
      <webElementGuid>6db65f5b-88d1-4808-9133-8dc8c1232086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-log-report']/div/div[2]/div/div/form/div/div/div[4]/div/div</value>
      <webElementGuid>d9b379e6-cf28-481e-87e6-e5690000626b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>5eff153a-bffd-4ad6-b019-354e219460aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pv_id_72' and (text() = 'Select time interval' or . = 'Select time interval')]</value>
      <webElementGuid>976b1803-c901-4256-861c-e222fa3e4c18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
