<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select listed by</name>
   <tag></tag>
   <elementGuidId>297cf11a-6f29-4cec-b1e1-a743106f789a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/main/div/div/div[2]/div/div/form/div[1]/div[1]/div[3]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_71</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9cbbd413-8556-46ac-a520-4b7bdd97ba5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>customvalidation</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>bf898a1b-26db-43f2-9524-e7858605bdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Listed by</value>
      <webElementGuid>546eb0cb-b916-4ab5-9286-65cdc5dddf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldname</name>
      <type>Main</type>
      <value>listedBy</value>
      <webElementGuid>63f8c39a-bdc3-49e4-839c-46031756cf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8f678c10-764f-423b-9345-8b4160091520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usevalidator</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22e815b8-7373-40a0-94b4-7df943b24c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mandatory</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8514724-91b5-49c2-a257-d712ca0a2c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formatvalidatormessage</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0984c9b9-dfc4-46c1-828f-a10583c157e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>Listed byerror</value>
      <webElementGuid>b89a898b-2a75-4e52-a3f8-7e3b32aaf3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex relative w-full cursor-default select-none</value>
      <webElementGuid>6ad6b863-e17b-431f-97a5-6d5cd38716e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-name</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ab477b39-ddeb-4eed-96dc-299858707fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>c227f36f-3410-4337-b7e7-f7422ee83b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_71</value>
      <webElementGuid>868f5fe7-da97-4326-a1c6-f530af37bd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select listed by</value>
      <webElementGuid>8c34f3de-db83-448e-a6e7-d9c00a13ef55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_71&quot;)</value>
      <webElementGuid>8f12289e-8a31-41f6-9538-8e2c30a6360c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pv_id_71']</value>
      <webElementGuid>fb1775bf-2088-469c-9e69-e461f5b9ec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@tagsamurai/ts-mfe-log-report']/div/div[2]/div/div/form/div/div/div[3]/div/div</value>
      <webElementGuid>2d738140-a440-49fb-97f5-8c3e74c087be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>c85e2b8d-03f7-4aeb-a3c2-d9ee228312d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pv_id_71' and (text() = 'Select listed by' or . = 'Select listed by')]</value>
      <webElementGuid>73d8bce0-ad22-481d-b98d-faddd6b51604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
