<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Group</name>
   <tag></tag>
   <elementGuidId>c059be35-35a2-44cf-b6b3-f13620a71227</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pv_id_71_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>16ead760-12ef-459a-9c2e-2775efe5682b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_71_0</value>
      <webElementGuid>8520b616-8557-4013-8d44-2fa6696ad85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>49acbfb0-601b-4a94-89fd-2352fb4c3b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>897cd473-382e-4c9e-ab22-88220151ce5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a51f1ca3-6502-405b-976f-0a381265cce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>35d0882d-b9b9-4f7e-95d8-aa779e820de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d86196ba-7c46-47df-a100-f92c22a6307b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ae0c5dc1-06a6-4f92-b088-cbfa6d7a9cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-highlight</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd895bac-aa3d-40f4-8855-ce28ea3d69c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19a79790-e532-4b95-9a40-01b145018334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b20d674b-8509-4e8a-8d2c-483f216a1c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs font-medium w-full overflow-hidden text-ellipsis relative border-0 rounded-none m-0 py-2 px-4 bg-surface-200 dark:bg-general-800 text-surface-700 dark:text-general-100 hover:bg-primary-bg-weak dark:hover:bg-general-700 hover:text-primary dark:hover:text-general-100 focus-visible:outline-none focus-visible:outline-offset-0 focus-visible:ring-1 focus-visible:ring-inset focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 cursor-pointer overflow-hidden whitespace-nowrap</value>
      <webElementGuid>773ada6d-3713-4762-ab20-386ef18e1a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>c12afe3c-71ef-4114-9557-678cb782bf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>42159c75-acd3-4310-bf8e-d253cac04917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_71_0&quot;)</value>
      <webElementGuid>39539801-efa0-4972-b424-40ed4f359db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_71_0']</value>
      <webElementGuid>3cf01678-39f9-4e8d-916a-4d10e8c2fac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_71_list']/li</value>
      <webElementGuid>c2980978-c1c2-4b14-9ba2-f4a8331d6ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/ul/li</value>
      <webElementGuid>f92185b0-154d-468e-9be6-1f32213f6585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_71_0' and (text() = 'Group' or . = 'Group')]</value>
      <webElementGuid>65ad8fe6-90ad-4594-9ff8-3fef79e8980b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
