<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Peralatan</name>
   <tag></tag>
   <elementGuidId>c46b8c9f-e822-4f06-ae5b-9b98382a7699</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pv_id_74_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pv_id_74_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>404773a4-e304-4798-835d-bd7f187050dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pv_id_74_2</value>
      <webElementGuid>e31ba3da-8d55-4a51-bf84-b11e1a5b236a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>00df0af5-6ed8-4ff3-9772-9851eb0e9dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Peralatan</value>
      <webElementGuid>ef9bc055-6f2b-416f-8440-d6ca4aa815f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aec2c580-407e-4d9d-8f6f-a952f03c9251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a007de67-ca2f-4e43-9aec-5d58e3d387dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>21ce5db0-ede6-4484-be51-7a1aee20f178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>78040627-1c20-4862-9402-1071b7412835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs font-medium flex items-center gap-2 relative border-0 rounded-none m-0 py-2 px-4 text-surface-700 dark:text-general-100 hover:bg-primary-bg-weak dark:hover:bg-general-700 hover:text-primary dark:hover:text-general-100 focus-visible:outline-none focus-visible:outline-offset-0 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary-500 dark:focus-visible:ring-primary-400 cursor-pointer overflow-hidden whitespace-nowrap</value>
      <webElementGuid>dacdeacc-e3ab-43ce-afb6-666f07b0c748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pc-section</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>4e831aab-0f8c-4a74-9856-e74097264662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-highlight</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7c3a1fe-c55b-4ddd-911d-f405883c80c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>862ab7b2-7d91-40c7-96e1-b361eb90fe23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-p-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d807bee-09b1-411c-8296-316113d00bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Peralatan</value>
      <webElementGuid>f5e75f7c-4f73-48f8-88b5-e996ac78146b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pv_id_74_2&quot;)</value>
      <webElementGuid>ac5e07ea-e968-49f9-93b2-f7fab0e5c32e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pv_id_74_2']</value>
      <webElementGuid>14b6f589-2fbe-426d-b0cd-005644618812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pv_id_74_list']/li[3]</value>
      <webElementGuid>bf9a74c3-4c90-43ad-8e6e-326e0fd1a6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]</value>
      <webElementGuid>87004dff-66be-4ce8-905c-fda647e929d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pv_id_74_2' and (text() = 'Peralatan' or . = 'Peralatan')]</value>
      <webElementGuid>73828bc2-a029-44f6-a6b0-63e8d7e025af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
